version: "3.8"

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
    - "../postgres/schema:/docker-entrypoint-initdb.d"
    

